name: substrate
description: Environmental Substrate for Multi-Device Progressive Applications.
version: 0.0.1
author: Ray King <taipan.king@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  changelog: "^1.3.2"
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.6.3"
  faker: "^0.0.2"
  glob: "^1.0.5"
  lookup_map: "^0.0.1"
  mustache: "^0.2.3"
  path: "^1.3.6"
  petitparser: "^1.4.3"
  test: '>=0.12.0 <0.13.0'
  validator: "^0.0.7"
  yaml: "^2.1.5"
